default:
  image: nasalib-ci:latest

stages:
  - test

test:
  stage: test
  script:
    - export PVS_LIBRARY_PATH=$CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR && ./install-scripts
    - cd $CI_PROJECT_DIR && ./prove-all
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/summaries/*
      - $CI_PROJECT_DIR/nasalib.grandtotals
    expire_in: 14 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'